#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

require 'racc/parser.rb'
class SmiteParser < Racc::Parser

module_eval(<<'...end smite_parser.y/module_eval...', 'smite_parser.y', 112)
  
def parse(str)
  @q = []
  until str.empty?
    case str
    when /\A\s+/
    when /\A(#{gods})/i
      @q.push [:GOD, $&.downcase]
    when /\A(#{items})/i
      @q.push [:ITEM, $&.downcase]
    when /\A\d+/
      @q.push [:NUM, $&.to_i]
    when /\A1st/i
      @q.push [:FIRST, $&.to_i]
    when /\A2nd/i
      @q.push [:SECOND, $&.to_i]
    when /\A3rd/i
      @q.push [:THIRD, $&.to_i]
    when /\A4th/i
      @q.push [:FOURTH, $&.to_i]
    when /\A5th/i
      @q.push [:FIFTH, $&.to_i]
    when /\Aability/i
      @q.push [:ABILITY, $&.downcase]
    when /\Aultimate/i
      @q.push [:FOURTH, '4th']
      @q.push [:ABILITY, 'ability']
    when /\Apassive/i
      @q.push [:PASSIVE, $&.downcase]
    when /\Aeffects/i
      @q.push [:EFFECTS, $&.downcase]
    when /\Awith/i
      @q.push [:WITH, $&.downcase]
    when /\A(base )?stats/i
      @q.push [:STATS, $&.downcase]
    when /\A(at )?level/i
      @q.push [:LEVEL, $&.downcase]
    when /\A(#{dmg_types})/i
      @q.push [:DMG_TYPE, $&.downcase]
    when /\A(#{atk_ranges})/i
      @q.push [:ATK_RANGE, $&.downcase]
    when /\A(#{roles})/i
      @q.push [:ROLE, $&.downcase]
    when /\A(#{pantheons})/i
      @q.push [:PANTHEON, $&.downcase]
    when /\A./
      @q.push [$&, $&]
    end
    str = $'
  end
  @q.push [false, '$end']
  do_parse
end

def dmg_types
  'physical|magic(al)?'
end

def atk_ranges
  'ranged|melee'
end

def roles
  @roles ||= Smite::Game.roles.join('|')
end

def pantheons
  @pantheons ||= Smite::Game.pantheons.join('|')
end

def gods
  @gods ||= Smite::Game.gods.map { |g| g.name.downcase.tr("'", '') }.join('|')
end

def items
  @items ||= Smite::Game.devices.map { |d| d.name.downcase.tr("'", '') }.join('|')
end

def next_token
  @q.shift
end

...end smite_parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     6,    17,    11,    12,    13,    14,     9,    19,    20,    21,
    22,    23,    24,    25,    26,    11,    12,    13,    14,    38,
    27,    30,    39,    31,    33,    32,    28,    34,    36,    37,
    15,    36,    41,    42,    39 ]

racc_action_check = [
     0,     6,     5,     5,     5,     5,     0,     6,     6,     6,
     6,     6,     6,     6,     9,     0,     0,     0,     0,    35,
     9,    17,    35,    17,    19,    18,    15,    30,    31,    34,
     1,    37,    38,    39,    40 ]

racc_action_pointer = [
    -2,    30,   nil,   nil,   nil,   -15,    -2,   nil,   nil,     4,
   nil,   nil,   nil,   nil,   nil,    26,   nil,    17,    16,    19,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    22,    20,   nil,   nil,    23,    15,   nil,    23,    27,    25,
    27,   nil,   nil ]

racc_action_default = [
   -33,   -33,    -1,    -2,    -3,    -4,    -5,    -6,    -7,   -24,
   -28,   -29,   -30,   -31,   -32,   -33,   -27,   -13,   -33,   -33,
   -18,   -19,   -20,   -21,   -22,   -23,   -25,   -26,    43,    -8,
   -33,   -33,   -16,   -17,   -12,   -11,   -15,   -33,   -33,   -33,
    -9,   -10,   -14 ]

racc_goto_table = [
    35,     7,    10,     4,     5,     3,    40,    16,     8,    29,
     2,    18,     1 ]

racc_goto_check = [
     9,     6,    11,     4,     5,     3,     9,    11,     7,     8,
     2,    10,     1 ]

racc_goto_pointer = [
   nil,    12,    10,     5,     3,     4,     1,     8,    -8,   -31,
     5,     2 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 22, :_reduce_none,
  1, 23, :_reduce_none,
  1, 23, :_reduce_none,
  1, 23, :_reduce_4,
  1, 24, :_reduce_5,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  3, 28, :_reduce_8,
  4, 29, :_reduce_9,
  4, 29, :_reduce_10,
  2, 29, :_reduce_11,
  2, 29, :_reduce_12,
  0, 29, :_reduce_13,
  3, 30, :_reduce_14,
  1, 30, :_reduce_15,
  3, 27, :_reduce_16,
  3, 27, :_reduce_17,
  2, 27, :_reduce_18,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 31, :_reduce_none,
  1, 25, :_reduce_24,
  2, 25, :_reduce_25,
  2, 25, :_reduce_26,
  2, 26, :_reduce_27,
  1, 26, :_reduce_none,
  1, 32, :_reduce_29,
  1, 32, :_reduce_30,
  1, 32, :_reduce_31,
  1, 32, :_reduce_32 ]

racc_reduce_n = 33

racc_shift_n = 43

racc_token_table = {
  false => 0,
  :error => 1,
  :GOD => 2,
  :STATS => 3,
  :LEVEL => 4,
  :NUM => 5,
  :WITH => 6,
  "," => 7,
  :ITEM => 8,
  :ABILITY => 9,
  :PASSIVE => 10,
  :FIRST => 11,
  :SECOND => 12,
  :THIRD => 13,
  :FOURTH => 14,
  :FIFTH => 15,
  :EFFECTS => 16,
  :DMG_TYPE => 17,
  :ATK_RANGE => 18,
  :ROLE => 19,
  :PANTHEON => 20 }

racc_nt_base = 21

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "GOD",
  "STATS",
  "LEVEL",
  "NUM",
  "WITH",
  "\",\"",
  "ITEM",
  "ABILITY",
  "PASSIVE",
  "FIRST",
  "SECOND",
  "THIRD",
  "FOURTH",
  "FIFTH",
  "EFFECTS",
  "DMG_TYPE",
  "ATK_RANGE",
  "ROLE",
  "PANTHEON",
  "$start",
  "target",
  "information",
  "god_info",
  "item_info",
  "search_info",
  "god_ability",
  "god_stats",
  "level_and_items",
  "item_list",
  "nth",
  "search_item" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

module_eval(<<'.,.,', 'smite_parser.y', 8)
  def _reduce_4(val, _values, result)
     result = result.to_a 
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 12)
  def _reduce_5(val, _values, result)
          result = Smite::Game.god(val[0])
    
    result
  end
.,.,

# reduce 6 omitted

# reduce 7 omitted

module_eval(<<'.,.,', 'smite_parser.y', 19)
  def _reduce_8(val, _values, result)
          result   = Smite::Game.god(val[0]).stats
      result   = result.at_level(val[2][:level]) if val[2][:level]
      result   = result.with_items(val[2][:items]) if val[2][:items]

      result
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 28)
  def _reduce_9(val, _values, result)
          result = { level: val[1], items: val[3] }
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 31)
  def _reduce_10(val, _values, result)
          result = { level: val[3], items: val[1] }
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 34)
  def _reduce_11(val, _values, result)
          result = { items: val[1] }
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 37)
  def _reduce_12(val, _values, result)
          result = { level: val[1]}
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 40)
  def _reduce_13(val, _values, result)
          result = {}
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 44)
  def _reduce_14(val, _values, result)
          result << Smite::Game.item(val[2])
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 47)
  def _reduce_15(val, _values, result)
          result = [Smite::Game.item(val[0])]
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 52)
  def _reduce_16(val, _values, result)
          which = (val[1] - 1) % 5
      result = Smite::Game.god(val[0]).abilities[which]
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 56)
  def _reduce_17(val, _values, result)
          which = (val[2] - 1) % 5
      result = Smite::Game.god(val[0]).abilities[which]
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 60)
  def _reduce_18(val, _values, result)
          result = Smite::Game.god(val[0]).abilities[4]
    
    result
  end
.,.,

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

module_eval(<<'.,.,', 'smite_parser.y', 67)
  def _reduce_24(val, _values, result)
          result = Smite::Game.item(val[0])
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 70)
  def _reduce_25(val, _values, result)
          result = Smite::Game.item(val[0]).passive
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 73)
  def _reduce_26(val, _values, result)
          result = Smite::Game.item(val[0]).effects
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 78)
  def _reduce_27(val, _values, result)
          result = Set.new(val[0]) & Set.new(val[1])
    
    result
  end
.,.,

# reduce 28 omitted

module_eval(<<'.,.,', 'smite_parser.y', 84)
  def _reduce_29(val, _values, result)
          result = Smite::Game.gods.select do |g|
        val[0] =~ /phys/ ? g.physical? : g.magic?
      end
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 89)
  def _reduce_30(val, _values, result)
          result = Smite::Game.gods.select do |g|
        val[0] =~ /melee/ ? g.melee? : g.ranged?
      end
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 94)
  def _reduce_31(val, _values, result)
          result = Smite::Game.gods.select do |g|
        val[0].downcase == g.role.downcase
      end
    
    result
  end
.,.,

module_eval(<<'.,.,', 'smite_parser.y', 99)
  def _reduce_32(val, _values, result)
          result = Smite::Game.gods.select do |g|
        val[0].downcase == g.pantheon.downcase
      end
    
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class SmiteParser

require 'set'
require 'smite'
